apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: drno
  name: drno
spec:
  containers:
  - image: nginx
    name: drno
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
