apiVersion: v1
kind: Pod
metadata:
  labels:
    run: drno
  name: drno
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
      - sleep
      - "1800"
    resources:
      requests:
        cpu: "0.3"
        #memory: "64Mi"
        memory: "128M"
      limits:
        cpu: "0.5"
        #memory: "128Mi"
        memory: "0.5G"
  dnsPolicy: ClusterFirst
  restartPolicy: Always